In [1]:
import os
import pickle
import numpy as np
from PIL import Image
from collections import OrderedDict
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 600
plt.rcParams['savefig.dpi'] = 600
import time

In [2]:
model_list = []

In [3]:
for file in os.listdir("./rotate"):
    if file.startswith("model_name_"):
        print(os.path.join("./rotate", file))
        with open(os.path.join("./rotate", file), "rb") as f:
            model_list_partial = pickle.load(f)
        for model in model_list_partial:
            model_list.append(model.split("/")[-2])
    #break

./rotate\model_name_0
./rotate\model_name_1000
./rotate\model_name_2000
./rotate\model_name_3000
./rotate\model_name_5000
./rotate\model_name_6000
./rotate\model_name_7000
./rotate\model_name_8000
./rotate\model_name_9000


In [6]:
syn_loss = np.zeros(shape=len(model_list))

In [9]:
for i, model in enumerate(model_list):
    #print(model)
    #break
    if i >= 1000:
        break
    if i >= 4000:
        idx = i + 1000
    else:
        idx = i
    for az in range(18):
        for el in range(3):
            real_img_path = "C:\\tmp\\test\\" + model + "\\" + model + "_az_" + str(az * 20) + "_el_" + str(el * 10) + "_albedo.png0001.png"
            syn_img_path = "./rotate/rotate/" + str(idx * 1000 + az * 10 + el) + ".0.jpg"
            realimg = np.array(Image.open(real_img_path).convert("RGB"))
            synimg = np.array(Image.open(syn_img_path))
            syn_loss[i] += np.mean(np.abs(realimg - synimg))
    syn_loss[i] /= 54
    print(syn_loss[i] / 256 * 3.)
    #break
print(np.mean(syn_loss) / 256. * 3)

0.3529939276200753
0.3151359050362197
0.42009911092384045
0.34674313088012826
0.2925921561623142
0.4095156386555958
0.3558433566891445
0.3028133924442391
0.30141866337942325
0.37010270218136226
0.28945749777334717
0.40281669740323656
0.2874121136135526
0.35575232682404695
0.27838818673734317
0.47858135788529016
0.3186986490532204
0.44263984538890705
0.2655599602946529
0.38883061320693413
0.3579021559821235
0.2586603959401448
0.4623315819987544
0.3957920471827189
0.38526614065523523
0.25136843875602444
0.2589695983462863
0.4094583458370633
0.3226687025140833
0.2309415649484705
0.2986695987206919
0.40104105295958337
0.3348603601808902
0.4587179775591247
0.40739268726772726
0.34308900656523533
0.4057835384651466
0.2755574915144179
0.286848545074463
0.30036864457307033
0.41826851721163144
0.2823591541360926
0.2911753036357739
0.25113263836613414
0.4121887154049344
0.3230456599482784
0.34426681200663245
0.3942931802184493
0.4380470955813373
0.25095710489485
0.36361085927044895
0.19994954709

0.43573022330248784
0.4044234443593908
0.4786859706596093
0.40770129804258
0.37405878526193115
0.4118262441069991
0.4800954041657624
0.35251428021324993
0.41268301010131836
0.3922377427419027
0.29043864320825646
0.44394750506789604
0.3618412415186564
0.29720529803523316
0.32377556959788006
0.4305314708639074
0.41179117450007685
0.26358826513643624
0.37015148445411966
0.3057631298347755
0.3314692444271511
0.2978262150729144
0.3725916456293176
0.3782381878958808
0.32527434825897217
0.2570341295666165
0.310812027366073
0.31905387949060515
0.28818908002641463
0.312825600306193
0.3853692301997431
0.2976125831957217
0.3973969441873054
0.3915287830211498
0.3894410928090414
0.359379839014124
0.42674879674558275
0.3475978551087555
0.4044525358412001
0.26785246531168616
0.30245474091282587
0.3736647102567884
0.31842182742224795
0.3763381595964784
0.3813616964552138
0.31784477057280375
0.38060787430515997
0.339194589191013
0.2770552811799226
0.286009603076511
0.3409514118123938
0.3671478607036449

0.2503979824207446
0.37269688094103776
0.42006970334936067
0.3470900588565402
0.3360167874230279
0.2814929617775811
0.30668620268503827
0.43961999151441794
0.3304935517134489
0.27031316580595793
0.3002056589833013
0.36772199913307474
0.32692487151534466
0.3482560669934308
0.3424327859172115
0.35497860555295596
0.35837352275848383
0.336556147646021
0.3684650571257979
0.43898389957569267
0.3654197057088218
0.39410368159965226
0.42198406325446236
0.37146258795702913
0.3047220442030166
0.2370318836636014
0.45020774117222545
0.44212672445509166
0.30154518286387116
0.3051598557719478
0.3933191431893242
0.3765999696872853
0.4006079700258044
0.3760211291136565
0.2781022742942527
0.32110204961564814
0.4159566031561958
0.4036889826809919
0.35464300049675834
0.23293574651082355
0.27387094939196543
0.34640023884949855
0.29654214117262107
0.25379741191864014
0.3705298061724063
0.27706642945607507
0.36936495480714016
0.31995484564039445
0.2795231342315674
0.45663035798955864
0.3190419409010145
0.372

In [ ]:
model_path = "C:\\Users\\AndrewHuang\\Documents\\GitHub\\02958343\\02958343"
refine_loss = np.zeros(shape=len(model_list))
for idx, model in enumerate(model_list):
    #print(model)
    #break
    os.system("blender --background --python 3dloc_2dcoor.py -- --views 18 " + os.path.join(model_path, model, "model.obj"))
    with open("./vertex2pixel", "rb") as f:
        vertex2pixel = pickle.load(f)
    with open("./pixel2vertex", "rb") as f:
        pixel2vertex = pickle.load(f)
    vertex2color = OrderedDict()
    for az in range(18):
        for el in range(3):
            real_img_path = "C:\\tmp\\test\\" + model + "\\" + model + "_az_" + str(az * 20) + "_el_" + str(el * 10) + "_albedo.png0001.png"
            syn_img_path = "./rotate/rotate/" + str(idx * 1000 + az * 10 + el) + ".0.jpg"
            synimg = np.array(Image.open(syn_img_path))
            realimg = np.array(Image.open(real_img_path).convert("RGB"))
            for i in range(128):
                for j in range(128):
                    if pixel2vertex[az, el, i, j, 0] != 1234567.0:
                        if not repr(pixel2vertex[az, el, i, j, 1:]) in vertex2color:
                            vertex2color[repr(pixel2vertex[az, el, i, j, 1:])] = []
                        vertex2color[repr(pixel2vertex[az, el, i, j, 1:])].append(synimg[i, j])
    for az in range(18):
        for el in range(3):
            real_img_path = "C:\\tmp\\test\\" + model + "\\" + model + "_az_" + str(az * 20) + "_el_" + str(el * 10) + "_albedo.png0001.png"
            syn_img_path = "./rotate/rotate/" + str(idx * 1000 + az * 10 + el) + ".0.jpg"
            realimg = np.array(Image.open(real_img_path).convert("RGB"))
            synimg = np.array(Image.open(syn_img_path))
            
            synimg_refined = np.copy(synimg)
            for i in range(128):
                for j in range(128):
                    if pixel2vertex[az, el, i, j, 0] != 1234567.0:
                        candidate_pixel = np.mean(vertex2color[repr(pixel2vertex[az, el, i, j, 1:])], axis=0).astype(realimg.dtype)
                        synimg_refined[i, j] = candidate_pixel
            refine_loss[idx] += np.mean(np.abs(realimg - synimg_refined))
            '''
            fig, axs = plt.subplots(1, 3)
            axs[0].imshow(realimg)
            axs[1].imshow(synimg)
            axs[2].imshow(synimg_refined)
            '''
    refine_loss[idx] /= 54
    print("synloss: ", syn_loss[idx], ", refinedloss: ", refine_loss[idx])
    if idx >= 1000:
        break
    
print(np.mean(refine_loss) / 256. * 3)

synloss:  30.122148490246424 , refinedloss:  29.786105309003673
synloss:  26.891597229757416 , refinedloss:  26.324140760633675
synloss:  35.84845746550105 , refinedloss:  32.64784749348958
synloss:  29.58874716843761 , refinedloss:  27.347946732132527
synloss:  24.96786399251748 , refinedloss:  24.239599534022958
synloss:  34.94533449861084 , refinedloss:  31.34985125506366
synloss:  30.365299770807 , refinedloss:  29.654202684944067
synloss:  25.840076155241736 , refinedloss:  30.77335084514854
synloss:  25.72105927504412 , refinedloss:  25.594258626302082
synloss:  31.58209725280958 , refinedloss:  33.492481749734765
synloss:  24.700373143325624 , refinedloss:  23.895706365137933
synloss:  34.373691511742855 , refinedloss:  31.488715654538005
synloss:  24.525833695023156 , refinedloss:  23.604705433786652
synloss:  30.35753188898534 , refinedloss:  32.491259916329085
synloss:  23.75579193491995 , refinedloss:  21.948024796850884
synloss:  40.83894253954476 , refinedloss:  38.4894458

In [39]:
vertex2color

OrderedDict([('array([ 0.0144346,  0.0875696, -0.155605 ])',
              [array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8)]),
             ('array([-0.41752499,  0.0467642 , -0.149501  ])',
              [array([0, 0, 0], dtype=uint8)]),
             ('array([-0.42677501,  0.051977  , -0.147256  ])',
              [array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8)]),
             ('array([-0.424694 ,  0.0560501, -0.145574 ])',
              [array([0, 0, 0], dtype=uint8)]),
             ('array([-0.42012101,  0.0344134 , -0.150932  ])',
              [array([0, 0, 0], dtype=uint8)]),
             ('array([-0.44897699,  0.013727  , -0.14967699])',
              [array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8),
               array([0, 0, 0], dtype=uint8),
              